### ISSUE TITLE
让div宽度根据内容来定

### ISSUE THREAD

**Issue by zhongDZ** [zhongDZ/zhongdz#14]
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="author" content="http://www.softwhy.com/" />
<title>测试</title>
<style type="text/css">
```
```css
.parent{
  width:400px;
  height:400px;
  border:1px solid red;
}
.children{
  border:1px solid blue;
  height:50px;
  display:inline-block;
  *display:inline;
  *zoom:1;
}
```
```html
</style>
</head>
<body>
<div class="parent">
  <div class="children">这里是一段测试的文字</div>
</div>
</body>
</html>
```
