### ISSUE TITLE
日常前端笔记

### ISSUE THREAD

**Issue by zhongDZ** [zhongDZ/zhongdz#8]
画三角形
```css
#triangle-up {
    width: 0;
    height: 0;
    border-left: 50px solid transparent;
    border-right: 50px solid transparent;
    border-bottom: 100px solid red;
}
```
```css
#triangle-down {
    width: 0;
    height: 0;
    border-left: 50px solid transparent;
    border-right: 50px solid transparent;
    border-top: 100px solid red;
}
```
###适配
####css3的缩放,配合
```html
<meta name="viewport" id="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
```
####rem
```css
html { font-size : 20px;}
```
##盒子模型

###ajax异步原理

```
XMLHttpRequest,是我们得以实现异步通讯的根本
XMLHttpRequest这个对象的属性。
XMLHttpRequest的属性有：
  　　onreadystatechange  每次状态改变所触发事件的事件处理程序。
  　　responseText     从服务器进程返回数据的字符串形式。
  　　responseXML    从服务器进程返回的DOM兼容的文档数据对象。
  　　status           从服务器返回的数字代码，比如常见的404（未找到）和200（已就绪）
  　　status Text       伴随状态码的字符串信息
  　　readyState       对象状态值
　　　　0 (未初始化) 对象已建立，但是尚未初始化（尚未调用open方法）
　　　　1 (初始化) 对象已建立，尚未调用send方法
　　　　2 (发送数据) send方法已调用，但是当前的状态及http头未知
　　　　3 (数据传送中) 已接收部分数据，因为响应及http头不全，这时通过responseBody和responseText获取部分数据会出现错误，
　　　　4 (完成) 数据接收完毕,此时可以通过通过responseXml和responseText获取完整的回应数据
Ajax的给我们带来的好处大家基本上都深有体会，在这里我只简单的讲几点：
    1、最大的一点是页面无刷新，在页面内与服务器通信，给用户的体验非常好。
　 2、使用异步方式与服务器通信，不需要打断用户的操作，具有更加迅速的响应能力。
　 3、可以把以前一些服务器负担的工作转嫁到客户端，利用客户端闲置的能力来处理，减轻服务器和带宽的负担，节约空间和宽带租用成本。并且减轻服务器的负担，ajax的原则是“按需取数据”，可以最大程度的减少冗余请求，和响应对服务器造成的负担。
    4、基于标准化的并被广泛支持的技术，不需要下载插件或者小程序。
状态码 200 就绪；404 找不到；502 繁忙；500 故障
```

###闭包原理
#####什么叫闭包 --->闭包就是一个拥有许多变量和绑定了这些变量的环境的表达式

```javascript
function a() { 
 var i = 0; 
 function b() { alert(++i); } 
 return b;
}
var c = a();
c();
```

###适配方案
http://www.cnblogs.com/samwu/p/4285748.html
http://www.w3ctech.com/topic/979
http://mdsa.51cto.com/art/201507/484215.htm ！！！！！！！！ 
1.固定宽度、
2.固定高度
3.响应式
4.流式
```
设置viewPoint进行缩放
流式布局、响应式布局、静态、自适应
响应式与自适应的原理是相似的，都是检测设备，根据不同的设备采用不同的css，而且css都是采用的百分比的，而不是固定的宽度，不同点是响应式的模板在不同的设备上看上去是不一样的，会随着设备的改变而改变展示样式，而自适应不会，所有的设备看起来都是一套的模板，不过是长度或者图片变小了，不会根据设备采用不同的展示样式，流式就是采用了一些设置，当宽度大于多少时怎么展示，小于多少时怎么展示，而且展示的方式向水流一样，一部分一部分的加载，静态的就是采用固定宽度的了
```
